subscription connectionUpdated {
    connectionUpdated {
        id,
        auth {
            status {
                authorized,
                complete
            },
            redirectUrl
        },
        name,
        enabled,
        last_run,
        permissions,
        provider_id,
        provider {
            id,
            name,
            auth_type,
            sources
        },
        provider_name,
        remote_connection_id
    }
}